#!/usr/bin/env bash

home=`pwd`
os=`uname`
echo $home
uname -a

function install_config {
    echo "** Installing config files"
    cp -vrT etc ~
    [ -L ~/s ] || ln -s ~/scripts ~/s

    sed -i /##DEBIAN##/,/####/d ~/.bash_aliases
    cat debian/.bash_aliases >> ~/.bash_aliases
    sed -i /##DEBIAN##/,/####/d ~/.oh-my-zsh/custom/techg.zsh
    cat debian/.bash_aliases >> ~/.oh-my-zsh/custom/techg.zsh
}

function install_base {
    echo "** Installing base software..."
    apt-get -y install build-essential cmake
    apt-get -y install curl
    apt-get -y install git 
    apt-get -y install powerline
    apt-get -y install python-dev python3-dev
    apt-get -y install rsync
    apt-get -y install sudo
    apt-get -y install wget
#   apt-get -y install atop
#   apt-get -y install byobu
#   apt-get -y install exuberant-ctags

    if [[ -z $DISPLAY ]]; then
        apt-get -y install vim-nox
    else
        apt-get -y install gitk git-gui
        apt-get -y install vim-gtk3
    fi
}

function install_chrome {
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - 
    sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
    apt-get update 
    apt-get install google-chrome-stable
}

function install_dev {
    echo "** Installing development packages..."
    apt-get -y install csstidy
    apt-get -y install tidy
}

function install_fonts {
    apt-get -y install fonts-powerline
    git clone https://github.com/powerline/fonts.git ~/fonts --depth=1
    ~/fonts/install.sh
    fc-cache -fv
    rm -fr ~/fonts
}

function install_net {
    echo "** Installing network packages..."
    apt-get -y install kismet
    apt-get -y install nmap
    if [[ -n $DISPLAY ]]; then
        apt-get -y install zenmap
        apt-get -y install wireshark
    fi
}

function install_vmware {
    apt-get -y install open-vm-tools 
    if [[ -n $DISPLAY ]]; then
        apt-get -y install open-vm-tools-desktop 
    fi
}

function init {
    echo 'Initializing base system...'
    apt update
    install_base
    install_fonts
    . plugins/tmux
    . plugins/zsh
    install_config
}

function plugins() {
    [[ -f "plugins/$1" ]] && . plugins/$1
}
# PROCESS ARGUMENTS

function usage() {
    echo "USAGE install [-u] [options]
    Options
    =======
    base   : Install base packages
    chrome : Install Chrome web browser
    config : Install configuration files
    dev    : Install development packages
    fonts  : Install fonts
    init   : Initialize base system
    net    : Install network tools
    vmware : Install vmware tools

    PLUGINS
    =======
    docker : Install Docker
    jitsi  : Install Jitsi Meet
    samba  : Install + Configure Samba Server
    tmux   : Install TMUX
    vim    : Build VIM
    zsh    : Install oh-my-zsh"
}

if [ "$1" == "-u" ]; then
    apt-get update
fi

[ $# == 0 ] && usage
for arg in $@
do
    case $arg in
        "base"   ) install_base;;
        "chrome" ) install_chrome;;
        "config" ) install_config;;
        "dev"    ) install_dev;;
        "fonts"  ) install_fonts;;
        "init"   ) init;;
        "net"    ) install_net;;
        "vmware" ) install_vmware;;
        *        ) plugins $arg;;
    esac
done

