##BASH##
alias a='alias'
alias df='df -h'
alias h='history' 
alias j='jobs -l' 
alias l='ls-lFh'
alias lS='ls -1FSsh'
alias la='ls -lAFh'
alias lart='ls -1Fcart'
alias ldot='ls -ld .*'
alias ll='ls -l'
alias lr='ls -tRFh'
alias lrt='ls -1Fcrt'
alias ls='ls --color=tty'
alias lsa='ls -lah'
alias lt='ls -ltFh'
alias m='less' 
alias t='tail -f'
####
