#!/usr/bin/env bash

echo -e "#\n# Installing Docker\n#\n\n"

# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install -y ca-certificates curl gpg
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor | sudo tee /etc/apt/keyrings/docker.gpg >/dev/null
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
. /etc/os-release

case $VERSION_CODENAME in
    kali-rolling | xia | zena) VERSION_CODENAME="trixie" ;;
esac

cat <<EOL | sudo tee /etc/apt/sources.list.d/docker.sources
Types: deb
URIs: https://download.docker.com/linux/debian 
Suites: trixie
Components: stable
Enabled: yes
Signed-By: /etc/apt/keyrings/docker.gpg
EOL

# echo \
  # "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $VERSION_CODENAME stable" |
  # sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo usermod -aG docker "$USER"

cd ~
git clone https://git.techg.ca/boomshankerx/docker
