#!/usr/bin/env bash

(
cd /tmp
curl -OLs https://github.com/espanso/espanso/releases/latest/download/espanso-debian-x11-amd64.deb
sudo apt install ./espanso-debian-x11-amd64.deb
sudo rm -f espanso-debian-x11-amd64.deb
)
espanso service register
espanso start