#!/usr/bin/env bash

curl -sS https://debian.griffo.io/EA0F721D231FDD3A0A17B9AC7808B4DD62C41256.asc | sudo gpg --dearmor --yes -o /etc/apt/keyrings/ghostty.gpg

cat <<EOF | sudo tee /etc/apt/sources.list.d/ghostty.sources
Types: deb
URIs: https://debian.griffo.io/apt
Suites: trixie
Components: main
Enabled: yes
Signed-By: /etc/apt/keyrings/ghostty.gpg
EOF

sudo apt update
sudo apt install -y ghostty

sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/ghostty 100
sudo update-alternatives --auto x-terminal-emulator