#!/usr/bin/env zsh

#
# KALITOOLS
#
echo "\n#\n# INSTALLING KALI-TOOLS\n#\n"
cd /opt

echo "# AutoRecon"
echo "# enum4linux-ng"
sudo git clone https://github.com/cddmp/enum4linux-ng.git
sudo ln -s $(pwd)/enum4linux-ng/enum4linux-ng.py /usr/local/bin/enum4linux-ng
echo "# nessus"
echo "# nmapAutomator"
sudo rm -r nmapAutomator
sudo git clone https://github.com/21y4d/nmapAutomator.git
sudo ln -s $(pwd)/nmapAutomator/nmapAutomator.sh /usr/local/bin/

echo "# nishang"
echo "# PowerSploit"


