#!/usr/bin/env zsh

#
# KALITOOLS
#
echo "\n#\n# INSTALLING KALI-TOOLS\n#\n"
sudo apt install ghidra

cd ~/scripts
git clone https://github.com/Dewalt-arch/pimpmykali ~/scripts/pimpmykali
git clone https://github.com/Green-m/msfvenom-zsh-completion ~/.oh-my-zsh/custom/plugins/msfvenom/

cd /opt
echo "# AutoRecon"

echo "# enum4linux-ng"
sudo git clone https://github.com/cddmp/enum4linux-ng.git
sudo ln -s $(pwd)/enum4linux-ng/enum4linux-ng.py /usr/local/bin/enum4linux-ng

echo "# nessus"

echo "# LinEnum"
sudo git clone https://github.com/rebootuser/LinEnum.git

echo "# nmapAutomator"
sudo git clone https://github.com/21y4d/nmapAutomator.git
sudo ln -s $(pwd)/nmapAutomator/nmapAutomator.sh /usr/local/bin/

echo "# OLEDUMP"

echi "# Windows Exploit Suggester"
sudo git clone https://github.com/AonCyberLabs/Windows-Exploit-Suggester.git

echo "# Windows Exploit Suggester NG"
sudo git clone https://github.com/bitsadmin/wesng.git
