#!/usr/bin/env zsh

#
# KALITOOLS
#

echo -e "#\n# Installing kalitools\n#\n\n"

mkdir ~/transfer

apps=(
    bloodyad
    cyberchef  
    dirsearch
    enum4linux-ng
    feroxbuster
    ligolo-ng
    name-that-hash
    ncat-w32
    remmina
    rlwrap
    sliver
)

for app in "${apps[@]}"; do
  echo "[*] Installing $app"
  sudo apt-get install -y "$app"
done

# Git Repos
cd ~
git clone https://github.com/Dewalt-arch/pimpmykali ~/pimpmykali

# pipx tools
echo -e "#\n# volatility3\n#\n\n"
pipx install volatility3
pipx install git+https://github.com/brightio/penelope


(
cd /opt

echo -e "#\n# hiati-hash\n#\n\n"
sudo gem install haiti-hash

echo -e "#\n# Windows Exploit Suggester\n#\n\n"
sudo git clone https://github.com/AonCyberLabs/Windows-Exploit-Suggester.git

echo -e "#\n# Windows Exploit Suggester NG\n#\n\n"
sudo git clone https://github.com/bitsadmin/wesng.git
)
