#!/usr/bin/env bash

curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
  | sudo tee /etc/apt/keyrings/ngrok.asc >/dev/null \

cat << EOF | sudo tee /etc/apt/sources.list.d/ngrok.sources 
Types: deb
URIs: https://ngrok-agent.s3.amazonaws.com
Suites: bookworm
Architectures: amd64
Components: main
Signed-By: /etc/apt/keyrings/ngrok.asc
EOF

sudo apt update 
sudo apt install ngrok
