#!/usr/bin/env bash

curl -sSL https://enterprise.proxmox.com/debian/proxmox-release-trixie.gpg -o /etc/apt/keyrings/proxmox-release-trixie.gpg

cat <<EOF > /etc/apt/sources.list.d/pbs-no-subscription.sources
Types: deb
URIs: http://download.proxmox.com/debian/pbs
Suites: trixie
Components: pbs-no-subscription
Signed-By: /etc/apt/keyrings/proxmox-release-trixie.gpg
EOF

sudo apt update && sudo apt upgrade -y
sudo apt install proxmox-backup-server
