#!/usr/bin/env zsh

#
# Syncthing
#

echo -e "#\n# Installing Syncthing\n#\n\n"

# Add the release PGP keys:
sudo curl -s -o /etc/apt/keyrings/syncthing.gpg https://syncthing.net/release-key.gpg
# Add the "stable" channel to your APT sources:
echo "deb [signed-by=/etc/apt/keyrings/syncthing.gpg] https://apt.syncthing.net/ syncthing stable-v2" | sudo tee /etc/apt/sources.list.d/syncthing.list
# Increase preference of Syncthing's packages ("pinning")
printf "Package: *\nPin: origin apt.syncthing.net\nPin-Priority: 990\n" | sudo tee /etc/apt/preferences.d/syncthing
# Update and install syncthing:
sudo apt update
sudo apt install -y syncthing
sudo apt install -y syncthing-gtk
