#!/usr/bin/env bash

sudo apt install wireguard

echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf

mkdir -m 0700 /etc/wireguard/
cd /etc/wireguard/

(umask 0700 && wg genkey | tee private.key | wg pubkey | tee public.key)

cat << EOF > wg0.conf
[Interface]
# Name = SERVER
PrivateKey = $(cat private.key) 
Address = 10.10.0.1/24 
ListenPort = 51820
PrivateKey = 
DNS = 
#Table = 12345
#MTU = 1500
#PreUp = /etc/wireguard/preup.sh
PostUp = /etc/wireguard/postup.sh 
#PreDown = /etc/wireguard/predown.sh
PostDown = /etc/wireguard/postdown.sh

[Peer]
# Name = 
PublicKey = 
AllowedIPs = 
Endpoint = 
PersistentKeepalive = 25

EOF
