# Remap prefix
unbind C-b
bind C-a send-prefix
set -g prefix C-a

set -g mouse on
set -g repeat-time 1000
set -g set-titles on
set -s escape-time 1
setw -g mode-keys vi

bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind \ split-window -h
bind - split-window -v
bind -r c-h select-window -t :-
bind -r c-l select-window -t :+
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R j


# Remap window navigation to vim
unbind-key j
bind-key j select-pane -D
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R

# POWERLINE
run-shell "powerline-daemon -q -r"
source /usr/share/powerline/bindings/tmux/powerline.conf
