# Remap prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g set-titles on
bind r source-file ~/.tmux.conf

# Remap window navigation to vim
unbind-key j
bind-key j select-pane -D
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R

# POWERLINE
run-shell "powerline-daemon -q"
source /usr/share/powerline/bindings/tmux/powerline.conf
